// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentRestAPI.Models;

namespace StudentRestAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StudentRestAPI.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("departmentId")
                        .HasColumnType("int");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Email = "joe@smaplemail.com",
                            FirstName = "Joe",
                            Gender = 0,
                            LastName = "Smith",
                            PhotoPath = "Images/joe.png",
                            departmentId = 1
                        },
                        new
                        {
                            StudentId = 2,
                            Email = "john@smaplemail.com",
                            FirstName = "John",
                            Gender = 0,
                            LastName = "Smith",
                            PhotoPath = "Images/john.png",
                            departmentId = 2
                        },
                        new
                        {
                            StudentId = 3,
                            Email = "james@smaplemail.com",
                            FirstName = "James",
                            Gender = 0,
                            LastName = "Johnson",
                            PhotoPath = "Images/james.png",
                            departmentId = 3
                        },
                        new
                        {
                            StudentId = 4,
                            Email = "john@smaplemail.com",
                            FirstName = "John",
                            Gender = 0,
                            LastName = "Doe",
                            PhotoPath = "Images/john.png",
                            departmentId = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
